version: '1.0'

services:
  customeraccountdb:
    container_name: customeraccountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=CustomerAccountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  customeraccount.api:
    container_name: customeraccount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=customeraccountdb;Port=5432;Database=CustomerAccountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - customeraccountdb
    ports:
      - "8002:80"
