version: '1.0'

services:
  customeraccountdb:
    image: postgres

  customeraccount.api:
    image: ${DOCKER_REGISTRY-}customeraccountapi
    build:
      context: .
      dockerfile: CustomerAccount.API/Dockerfile

volumes:
  postgres_data: