version: '1.0'

services:
  customeraccountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4  

  portainer:
    image: portainer/portainer-ce

  customeraccount.api:
    image: ${DOCKER_REGISTRY-}customeraccountapi
    build:
      context: .
      dockerfile: CustomerAccount.API/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
  elasticsearch-data:
 